### PR TITLE
fix default rake tasks

### PR DESCRIPTION
**Pull request by grosser**
@blowmage @wwood

can you turn travis on too at https://travis-ci.org/profile

### CODE REVIEW

**Comment by grosser** [comment]
@blowmage @wwood

**Comment by grosser** [comment]
@blowmage @wwood

**Comment by wwood** [comment]
Thanks, when this is merged I'll update the guix definition.

**Comment by blowmage** [comment]
I cherry-picked some commits from this PR, but I did not accept all of them. The test task now shells out to a script to run the 4 types of test output, and checks that the output has the appropriate colors. This means that all the tests now pass.

If you want to see the 4 types of test output you can run `rake sanity` to invoke scripts and see the pretty colors.

**Comment by grosser** [comment]
Thx, looks good :)

**Pull request closed without merging**
